---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: UserPortal
  labels:
    app: UserPortal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UserPortal
  template:
    metadata:
      labels:
        app: UserPortal
    spec:
      containers:
        - name: UserPortal
          image: username/UserPortal:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DocumentParser
  labels:
    app: DocumentParser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DocumentParser
  template:
    metadata:
      labels:
        app: DocumentParser
    spec:
      containers:
        - name: DocumentParser
          image: username/DocumentParser:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: VerificationAnalyzer
  labels:
    app: VerificationAnalyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VerificationAnalyzer
  template:
    metadata:
      labels:
        app: VerificationAnalyzer
    spec:
      containers:
        - name: VerificationAnalyzer
          image: username/VerificationAnalyzer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: TenantBilling
  labels:
    app: TenantBilling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TenantBilling
  template:
    metadata:
      labels:
        app: TenantBilling
    spec:
      containers:
        - name: TenantBilling
          image: username/TenantBilling:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: UserPortal
  labels:
    app: UserPortal
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: UserPortal


---


apiVersion: v1
kind: Service
metadata:
  name: DocumentParser
  labels:
    app: DocumentParser
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DocumentParser


---


apiVersion: v1
kind: Service
metadata:
  name: VerificationAnalyzer
  labels:
    app: VerificationAnalyzer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: VerificationAnalyzer


---


apiVersion: v1
kind: Service
metadata:
  name: TenantBilling
  labels:
    app: TenantBilling
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: TenantBilling

