apiVersion: v1
kind: Service
metadata:
  name: VerificationAnalyzer
  labels:
    app: VerificationAnalyzer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: VerificationAnalyzer